version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
    - npm install  -g npm
    - npm install  -g serverless
    - npm install  -g typescript
    - npm install  -g ts-node
    
  pre_build:
    commands:
    - npm install

    build:
    commands:
    - mkdir -p target/stg
    - mkdir target/prod
    - serverless package --package target/stg --stage stg -v -r ap-south-1
    - serverless package --package target/prod --stage prod -v -r ap-south-1

artifacts:
  files:
  - target/**/*
  - serverless.ts
  - deploy.sh